# Clippy configuration for Worknest

# Deny these lints
warn-on-all-wildcard-imports = true

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Too many arguments threshold
too-many-arguments-threshold = 7

# Type complexity threshold
type-complexity-threshold = 250
