name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build and Release Web App
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Cache wasm-pack
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/wasm-pack
          key: ${{ runner.os }}-wasm-pack-${{ hashFiles('~/.cargo/bin/wasm-pack') }}
          restore-keys: |
            ${{ runner.os }}-wasm-pack-

      - name: Install wasm-pack
        run: |
          if ! command -v wasm-pack &> /dev/null; then
            cargo install wasm-pack
          fi

      - name: Build web application
        run: ./build-webapp.sh release

      - name: Display build size
        run: |
          echo "Web application build size:"
          du -sh dist/
          echo ""
          echo "WASM file size:"
          find dist/ -name "*.wasm" -exec ls -lh {} \;

      - name: Create archive
        run: |
          cd dist
          tar czf ../worknest-web.tar.gz *
          cd ..

      - name: Generate checksums
        run: sha256sum worknest-web.tar.gz > worknest-web.tar.gz.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            worknest-web.tar.gz
            worknest-web.tar.gz.sha256
          body: |
            ## Worknest Web Application Release

            This release contains the web application built for WASM.

            ### Installation
            1. Download `worknest-web.tar.gz`
            2. Verify with `worknest-web.tar.gz.sha256`
            3. Extract: `tar xzf worknest-web.tar.gz`
            4. Serve the files with a web server
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
